### ISSUE TITLE
Dialog fdkTemplate="subheader" is cut off at the top

### ISSUE THREAD

**Issue by djumalin** [SAP/fundamental-ngx#10217]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
dialog subheader must be fully displayed

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
angular v15.0.3
node v18.14.2
fundamental-ngx v0.42.0

#### If this is a bug, please provide steps for reproducing it.
I've implemented a complex dialog by [example](https://fundamental-ngx.netlify.app/#/core/dialog).
Subheader get's cut off at the top.

Same behaviour happens in example "Complex Dialog" via StackBlitz.
![image](https://github.com/SAP/fundamental-ngx/assets/31624278/4877d217-5488-4948-8467-dd1bf7d1d4b3)

#### Please provide relevant source code if applicable.
Screenshot from StackBlitz page:
<img width="542" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/31624278/23277e10-d19f-4afc-b77a-937225d39058">

Screenshot from our page:
<img width="468" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/31624278/7c2883eb-f031-4c77-8700-2ab8965502fb">

**Comment by N1XUS** [comment]
@djumalin Looks like it's being fixed in last RC:
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/d9ea092d-4bb8-41b3-a98b-c55e740f5265)
Could you please confirm?

**Comment by mikerodonnell89** [comment]
@djumalin yes this was fixed with https://github.com/SAP/fundamental-ngx/pull/9770

Can we see your package.json file? This was fixed several releases ago

**Comment by djumalin** [comment]
Hey here is our package.json:
```
  "engines": {
    "node": ">=18.12.1 <19",
    "npm": ">=8.19"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.2.4",
    "@angular-eslint/builder": "15.2.1",
    "@angular-eslint/eslint-plugin": "15.2.1",
    "@angular-eslint/eslint-plugin-template": "15.2.1",
    "@angular-eslint/schematics": "15.2.1",
    "@angular-eslint/template-parser": "15.2.1",
    "@angular/cli": "~15.2.4",
    "@angular/compiler-cli": "^15.2.5",
    "@commitlint/cli": "^17.5.1",
    "@types/jasmine": "~4.3.0",
    "@typescript-eslint/eslint-plugin": "^5.57.1",
    "@typescript-eslint/parser": "^5.57.1",
    "cypress": "^12.9.0",
    "eslint": "^8.37.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-cypress": "^2.13.2",
    "eslint-plugin-license-header": "^0.6.0",
    "husky": "^8.0.3",
    "jasmine-core": "^5.0.1",
    "json-server": "^0.17.3",
    "karma": "^6.4.1",
    "karma-chrome-launcher": "^3.2.0",
    "karma-coverage": "^2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "^2.1.0",
    "karma-junit-reporter": "^2.0.1",
    "karma-mocha-reporter": "^2.2.5",
    "karma-webdriver-launcher": "^1.0.8",
    "lint-staged": "^13.2.0",
    "prettier": "^3.0.0",
    "start-server-and-test": "^2.0.0",
    "stylelint": "^15.4.0",
    "stylelint-config-standard-scss": "^10.0.0",
    "stylelint-prettier": "^4.0.0",
    "typescript": "^4.9.5"
  },
```

I also tried with `0.43.0-rc.28`, issue is still there.

**Comment by djumalin** [comment]
@mikerodonnell89 Hey i see the pr https://github.com/SAP/fundamental-ngx/pull/10264 but milestone for that pr was closed 4 days ago. Do you know when we can expect the fix to be released?

**Comment by mikerodonnell89** [comment]
@djumalin I've just merged the PR so it will be available in the latest RC version. I will also downport to our ng15 version of the library
