### ISSUE TITLE
[P2][Sourcing][Accessibility][JAWS][Tree table]Navigational issue with JAWS virtual cursor mode

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10279]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
 With the virtual cursor of JAWS it is not possible to navigate structured through the table (Ctrl+Alt+Arrow keys). The problem also occurs with JAWS 2023, but not with NVDA.
Virtual cursor pc mode expectation -
Next Cell in Row	ALT+CTRL+RIGHT ARROW
Prior Cell in Row	ALT+CTRL+LEFT ARROW
Cell Below in Column	ALT+CTRL+DOWN ARROW
Cell Above in Column	ALT+CTRL+UP ARROW

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
replicable on NGX tree table sample https://sap.github.io/fundamental-ngx/#/platform/table/basic#tree

#### If this is a bug, please provide steps for reproducing it.
1) Open JAWS
2) switch to virtual cursor mode
3) Try to traverse through table cells

#### Is there anything else we should know?
Reported by customers

**Comment by nikolay-kolarov** [comment]
Hi,

I tested and also observed the same. Upon doing some debugging and comparing with the tree in UI5, I noticed that the role="row" is missing on the <tr> elements. And although we are not adviced to double the semantics this solves the issue in this case and it is also present in the Ui5 implementation. Therefore my advice is also to add it here.
I noticed also one other thing - the aria-expanded in UI5 is on row level and here it was added on the gridcell containing the expansion icon.

Best Regards,
Nikolay

**Comment by droshev** [comment]
fixed with `0.43.8`

**Comment by sagar7259** [comment]
@droshev,

The issue is still not fixed. The cells of tree table cannot be navigated using Alt+Ctrl+Right/left arrow keys in JAWS Virtual PC cursor mode.

On using these key combinations only information read is "Beginning of row" and "End of row"
This still needs to be fixed.

@rvamudha could you please reopen this ticket.

Regards,
Sagar

**Comment by nikolay-kolarov** [comment]
https://github.com/SAP/fundamental-ngx/assets/17043004/d0728589-7bdd-4fb8-9ff4-d04aced57a13

**Comment by sagar7259** [comment]
Hi Team,

The key combinations alt+ctrl+arrow keys seems to be working fine after reverification. Hence this ticket can be closed.

@nikolay-kolarov thanks for the video.

Regards,
Sagar
