### ISSUE TITLE
[P2][Sourcing][Accessibility][Platform tree table][a11y help]Intially all checkboxes with TAB key get the focus (is wrong).

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10277]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
 Initially all checkboxes with TAB key get the focus (is wrong).
This was reported by customer directly on NGX tree table website

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
https://sap.github.io/fundamental-ngx/#/platform/table/basic#tree first column checkbox
This is also applicable on multi-select table

#### If this is a bug, please provide steps for reproducing it.
1) Reach the table using tab key
2) keep pressing tab key
3) Notice that all checkboxes start getting focus

#### Is there anything else we should know?
This is raised by customers directly for NGX website component

**Comment by nikolay-kolarov** [comment]
The tree table in UI5 can be used a reference: https://ui5.sap.com/resources/sap/ui/documentation/sdk/index.html?sap-ui-xx-sample-id=sap.ui.table.sample.TreeTable.JSONTreeBinding&sap-ui-xx-sample-lib=sap.ui.table&sap-ui-xx-sample-origin=.&sap-ui-xx-dk-origin=https%3A%2F%2Fui5.sap.com&sap-ui-theme=sap_horizon_dark&sap-ui-rtl=false&sap-ui-density=sapUiSizeCozy

**Comment by droshev** [comment]
fixed with `0.43.9`

**Comment by sagar7259** [comment]
Hello,

This issue is still not fixed, has all the checkboxes are still under tab key navigation initially which is wrong and this needs to be fixed.

@rvamudha please reopen the ticket.

Regards,
Sagar

**Comment by droshev** [comment]
@sagar7259 which version did you test that on?

**Comment by sagar7259** [comment]
Hi Team,

The issue is fixed with version 1.43, now the navigation order is working as expected, hence this ticket can be closed.

Regards,
Sagar
