### ISSUE TITLE
[P1][Sourcing][Accessibility][Table][a11y help] The column headers are marked with aria-haspopup. But no menu can be opened over them. They also refer to an empty element via aria-controls.

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10284]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The column headers are marked with aria-haspopup. But no menu can be opened over them. They also refer to an empty element via aria-controls.

#### If this is a bug, please provide steps for reproducing it.
This case is not applicable for table which dont have sort , filter etc, hence the aria property has to be updated for such cases.
And enabled only when sorting is true for those columns.

<img width="1472" alt="Screenshot 2023-08-03 at 9 38 24 PM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/a3f85624-5c8a-4539-a6c8-e04678ec06d1">

#### Is there anything else we should know?
Reported by customer

**Comment by droshev** [comment]
more input and context is needed

**Comment by droshev** [comment]
We need to downport to `ng15`

**Comment by I543348** [comment]
ATL Re-verification needed

**Comment by droshev** [comment]
fixed with `0.43.8`

**Comment by sagar7259** [comment]
Hello,

This was verified for simple table and the issue still exists. here the column headers are marked with aria-haspopup. But no menu can be opened over them. They also refer to an empty element via aria-controls.
https://sap.github.io/fundamental-ngx/#/platform/table/basic#tree

@rvamudha could you please reopen this ticket.?

Regards,
Sagar
