### ISSUE TITLE
[P1][Sourcing][Accessibility][Vertical Navigation][a11y help]Wrong state of the list item read for child nodes

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10389]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Wrong state of the list item read for child nodes 
Even though the parent node is expanded , when focus is on child list item , the screenreader reads "collapsed"

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
replicable on https://fundamental-ngx.netlify.app/#/core/vertical-navigation

#### If this is a bug, please provide steps for reproducing it.

<img width="1792" alt="Screenshot 2023-08-23 at 4 09 09 PM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/033182d0-a876-4f87-a3b8-12d90f805a68">

**Comment by droshev** [comment]
fixed with `0.43.8`

**Comment by sagar7259** [comment]
Hello,

This issue is still not fixed, has now accessing the child list items additional information "Closed" is being read for all the child items which is still creating confusion same as the information "collapsed". Hence this needs to be fixed.

@rvamudha please reopen this ticket.

Regards,
Sagar

**Comment by droshev** [comment]
The reported request has been done. This is a separate topic, which we would need to discuss and analyze with the accessibility expert first. Please, report a new issue.

**Comment by sagar7259** [comment]
Hello,
The issue is no more reproducible, the state of the children and parents are being read correctly. hence this ticket can be closed.

Regards,
Sagar (ATL Team)
