### ISSUE TITLE
[Sourcing][P1] New rows are misordered in the fdp-table with infinite scroll and tree data

### ISSUE THREAD

**Issue by Sayandeep-123** [SAP/fundamental-ngx#12070]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
When expanding any rows and scrolling down to load the next set of data (infinite scroll), the new rows are not being added in the correct position within the table.

The new rows fetched should be added in correct position

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular - 15
Fundamental Library - 0.43.35

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

Steps to reproduce:

1. Create an `fdp-table` with a tree data structure with child data source and implement infinite scroll.
2. Expand one or two rows.
3. Scroll down in the table to fetch the next set of data.
4. Observe that the new rows are not ordered correctly.
<img width="709" alt="Screenshot 2024-07-04 at 10 59 41 AM" src="https://github.com/SAP/fundamental-ngx/assets/71999626/204ae723-e6d8-43fa-8a9c-6c632d533f07">

#### Please provide relevant source code (if applicable).
Please check this piece:
https://github.com/SAP/fundamental-ngx/blob/7418a7c27de3daaf9222c16c296ff6ae11e13611/libs/platform/table/table.component.ts#L1725

Looks like proper index is not calculated (seems if any children rows are expands those are not considered in the while calculating the index) while inserting new rows.

#### Please provide stackblitz example(s).
Stackblitz link - [Click here](https://stackblitz.com/edit/angular-rvez99?file=src%2Fapp%2Fadvanced-scrolling-example.component.ts)

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by CSEHoangV** [comment]
This can be easier to reproduce if you expand children near the point of lazying load from parent level. Then, the lazy-loading point will not be consistent and append incorrect rows:

NG15 playground:

https://github.com/SAP/fundamental-ngx/assets/162270184/86611c5f-701d-4534-89d4-e09961dc21c9

NG15 playground on stackblitz with more level (https://stackblitz.com/edit/angular-1zjnv5?file=package.json):

https://github.com/SAP/fundamental-ngx/assets/162270184/685d806b-0d68-47b2-8e64-07c99db01b2b

Main branch (without latest sync from change in NG15):

https://github.com/SAP/fundamental-ngx/assets/162270184/ecf21cc9-39be-4617-9849-cc7281afda80

**Comment by mikerodonnell89** [comment]
@CSEHoangV thank you, I think all of these have been addressed now on the PR #12089

**Comment by CSEHoangV** [comment]
> @CSEHoangV thank you, I think all of these have been addressed now on the PR #12089

Hi Mike, I can still reproduce the issue:

https://github.com/SAP/fundamental-ngx/assets/162270184/16bfb28a-7cf0-4310-9bf2-d9fa12533630
