### ISSUE TITLE
Multi value component does not work well with async data

### ISSUE THREAD

**Issue by konradkukier2** [SAP/fundamental-ngx#650]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

Multi value component does not work well with async data

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

`fiori-fundamentals 1.4.5`
`fundamental-ngx 0.2.0`

#### If this is a bug, please provide steps for reproducing it.

When multi values is filled with static data - works as expected.

When data comes asynchronously  - it does not react properly on changes (ui reacts too fast, then doesnt pick up on new data, ending up with being one result set behind)

#### Please provide relevant source code if applicable.

`template.html`

```
  <h1>[persons$ length]: {{ (persons$ | async)?.length }}</h1>

  <fd-multi-input
    [dropdownValues]="persons$ | async"
    [placeholder]="'Search here...'"
    [(ngModel)]="selected"
    [displayFn]="displayFormatFn"
    (searchTermChange)="searchTermChanged($event)"
  >
  </fd-multi-input>
  Selected: {{ selected | json }}
```

`persons$` observable  is being notified on `searchTermChange` callback (which triggers async call)

#### Is there anything else we should know?

![async-values](https://user-images.githubusercontent.com/12159534/55156192-9083b280-5159-11e9-9836-c3e2450aa4e4.gif)

**Comment by MattL75** [comment]
Fixed as of 0.3.0

**Comment by konradkukier2** [comment]
This should be reopened. Its fixed to some extent, but still broken.

1) `maxHeight` value seems to not work
2) if number of results is high enough to not fit in a view, something is breaking

![multi-input2](https://user-images.githubusercontent.com/12159534/55727849-34e7dd80-5a13-11e9-935e-8c038d8cb728.gif)

You can see that for small dataset (that fits the view) it works ok:

![multi-input3](https://user-images.githubusercontent.com/12159534/55727920-5943ba00-5a13-11e9-8793-c25251669799.gif)

>     "fiori-fundamentals": "^1.5.1",
>     "fundamental-ngx": "^0.3.3",

my component usage

```
      <fd-multi-input
        [maxHeight]="'300px'"
        [dropdownValues]="persons$ | async"
        [placeholder]="'Search here...'"
        [(ngModel)]="selected"
        [displayFn]="displayFormatFn"
        (searchTermChange)="searchTermChanged($event)"
      >
      </fd-multi-input>
```

**Comment by MattL75** [comment]
The issue with the maxHeight is caused by our integration of Popper.js. It's just a matter of putting the maxHeight on another element.

As for the second issue, that's just Popper.js making calculations and finding that no matter how it arranges the popover, there's not enough room. Just having a functioning maxHeight is probably a sufficient fix.

**Comment by MattL75** [comment]
@konradkukier2 Yeah so closed by the PR, but could you test with the RC build if that's a good enough solution for your use-case?

**Comment by konradkukier2** [comment]
> t's just a matter of putting the maxHeight on another element.

Can you elaborate? If by that you mean to set `max-height` for wrapper via regular styling, then it didnt have any effect

**Comment by MattL75** [comment]
The RC build just finished 2 minutes ago - are you on  0.4.0-rc.6?

**Comment by konradkukier2** [comment]
works good 🚀

**Comment by MattL75** [comment]
Perfect! :D
